apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops
        image: us-central1-docker.pkg.dev/airy-semiotics-465715-j3/mlops/mlops:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
