version: 2.1

jobs:
  build_and_push:
    machine:  # ✅ Use full VM with Docker preinstalled
      image: ubuntu-2204:current
    steps:
      - checkout

      # Install gcloud SDK
      - run:
          name: Install Google Cloud SDK
          command: |
            sudo apt-get update && sudo apt-get install -y curl gnupg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      # Authenticate with GCP
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker us-central1-docker.pkg.dev -q

      # Build and Push Docker image
      - run:
          name: Build & Push Docker Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest

workflows:
  build-deploy:
    jobs:
      - build_and_push
