version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  build_docker_image:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - gcp-cli/setup
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker us-central1-docker.pkg.dev
      - run:
          name: Build and Push Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops/mlops:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops/mlops:latest

  deploy_to_gke:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - gcp-cli/setup
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
      - run:
          name: Configure GKE
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f kubernetes_deployment.yml

workflows:
  deploy_pipeline:
    jobs:
      - build_docker_image
      - deploy_to_gke:
          requires:
            - build_docker_image
