version: 2.1

executors:
  gcp-docker-executor:
    docker:
      - image: google/cloud-sdk:slim
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: gcp-docker-executor
    steps:
      - checkout

      # Enable Docker-in-Docker
      - setup_remote_docker

      # Authenticate with GCP
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker us-central1-docker.pkg.dev -q

      # Build and Push Docker Image
      - run:
          name: Build & Push Docker Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-app/mlops-app:latest

workflows:
  build-deploy:
    jobs:
      - build_and_push
